### ISSUE TITLE
Image example crashes

### ISSUE THREAD

**Issue by qarmin** [redox-os/orbtk#319]
Orbtk "0.3.1-alpha4" 2ca5c6efe1f9f2d91fe5955b6f0d09056e9e0f51
Ubuntu 20.04 X11

```
RUST_BACKTRACE=1 cargo run --example image
```
Image example crashes with following backtrace
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Could not load image."', crates/render/src/raqote/image.rs:94:29
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:217
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  11: rust_begin_unwind
             at src/libstd/panicking.rs:437
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1269
  14: core::result::Result<T,E>::unwrap
             at /home/rafal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:1005
  15: <orbtk_render::platform::image::Image as core::convert::From<&str>>::from
             at crates/render/src/raqote/image.rs:94
  16: <T as core::convert::Into<U>>::into
             at /home/rafal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/convert/mod.rs:560
  17: <&str as orbtk_api::properties::IntoPropertySource<orbtk_render::platform::image::Image>>::into_source
             at crates/api/src/macros.rs:35
  18: orbtk_widgets::image_widget::ImageWidget::image
             at ./crates/api/src/macros.rs:354
  19: image::main::{{closure}}
             at examples/image.rs:13
  20: orbtk_api::application::window_adapter::create_window
             at ./crates/api/src/application/window_adapter.rs:257
  21: orbtk_api::application::Application::window
             at ./crates/api/src/application/mod.rs:67
  22: image::main
             at examples/image.rs:7
  23: std::rt::lang_start::{{closure}}
             at /home/rafal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  24: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  25: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  26: std::panicking::try
             at src/libstd/panicking.rs:325
  27: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  28: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  29: std::rt::lang_start
             at /home/rafal/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  30: main
  31: __libc_start_main
  32: _start

```

**Comment by FloVanGH** [comment]
Ok thank you I will check it.
