### ISSUE TITLE
OrbTk widgets example panics when pressing "del" in a textbox and one off to right delete behavior

### ISSUE THREAD

**Issue by arctic-alpaca** [redox-os/orbtk#340]
**Describe the bug**

- The OrbTk widgets example panics when pressing `del` in an empty `Textbox`.

- Writing `1234567890` into a textbox and pressing `del` deletes the character one to the right of the supposed one.
`1234|567890` -> `del` -> `1234|57890`

**To Reproduce**
1. git clone https://github.com/redox-os/orbtk.git
2. cd orbtk
3. cargo run --example widgets --release
4. click on one of the textboxes
5. press `del`
6. panic

or 

5. type `1234567890` into a textbox
6. position cursor somewhere left of the middle
7. press `del`
8. character two to the right of the curser gets deleted

**Expected behavior**
Nothing should happen.
or
Character right to the cursor should be deleted

**Desktop (please complete the following information):**
 - OS: Window 10 home 1909

**Additional context**

<details><summary>Backtrace with empty textbox</summary>
<p>

```

     Running `target\release\examples\widgets.exe`
thread 'main' panicked at 'removal index (is 1) should be < len (is 0)', src\liballoc\vec.rs:1062:13
stack backtrace:
   0:           0x75423b - backtrace::backtrace::dbghelp::trace::ha09940ef4b8fd9a2
                               at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/dbghelp.rs:88
   1:           0x75423b - backtrace::backtrace::trace_unsynchronized::h19d7d1b30f96fe6c
                               at C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.46\src\backtrace/mod.rs:66
   2:           0x75423b - std::sys_common::backtrace::_print_fmt::hf038dfff95c497df
                               at src\libstd\sys_common/backtrace.rs:78
   3:           0x75423b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he2295693089d2e8c
                               at src\libstd\sys_common/backtrace.rs:59
   4:           0x77fbdc - core::fmt::write::h2e7468e40976ea37
                               at src\libcore\fmt/mod.rs:1076
   5:           0x7458d9 - std::io::Write::write_fmt::hef3158223e737cb6
                               at src\libstd\io/mod.rs:1537
   6:           0x758a70 - std::sys_common::backtrace::_print::he4a39cb956ba394d
                               at src\libstd\sys_common/backtrace.rs:62
   7:           0x758a70 - std::sys_common::backtrace::print::h38d45a7d7a4d1f02
                               at src\libstd\sys_common/backtrace.rs:49
   8:           0x758a70 - std::panicking::default_hook::{{closure}}::hfcc0d2f90e4d71be
                               at src\libstd/panicking.rs:198
   9:           0x7586f9 - std::panicking::default_hook::h7e61c8ee936a661d
                               at src\libstd/panicking.rs:217
  10:           0x7591ad - std::panicking::rust_panic_with_hook::h8b0608bd552a3d13
                               at src\libstd/panicking.rs:526
  11:           0x758dc4 - rust_begin_unwind
                               at src\libstd/panicking.rs:437
  12:           0x77c520 - core::panicking::panic_fmt::h858651244c7bf662
                               at src\libcore/panicking.rs:85
  13:           0x77435b - alloc::vec::Vec<T>::remove::assert_failed::hfee89c9707da1e63
                               at src\liballoc/vec.rs:1062
  14:           0x7036fc - orbtk_utils::string16::String16::remove::h2b41f1d56e830ba7
  15:           0x557594 - <orbtk_widgets::behaviors::text_behavior::TextBehaviorState as orbtk_api::widget_base::state::State>::update::h6d1164485f5bfd2f
  16:           0x57855a - <orbtk_api::systems::event_state_system::EventStateSystem as dces::system::System<orbtk_tree::Tree,dces::component::string_component_store::StringComponentStore,orbtk_render::platform::RenderContext2D>>::run_with_context::h64eebdbb1eb96b45
  17:           0x5bdf57 - dces::world::World<E,C,Ctx>::run_with_context::he2fb1ff7c371b506
  18:           0x56746a - orbtk_shell::platform::Shell<A>::run::h7e0340b60bda659c
  19:           0x57f772 - orbtk_api::application::Application::run::h8a2c1e635cfd2264
  20:           0x443e86 - widgets::main::h459a855d5e3f7549
  21:           0x45ef96 - std::rt::lang_start::{{closure}}::h1ac19ad8898282a6
  22:           0x75946c - std::rt::lang_start_internal::{{closure}}::hcfe58f53feea7233
                               at src\libstd/rt.rs:52
  23:           0x75946c - std::panicking::try::do_call::hc4163588b8559d85
                               at src\libstd/panicking.rs:348
  24:           0x75946c - std::panicking::try::h310a3be58418d841
                               at src\libstd/panicking.rs:325
  25:           0x75946c - std::panic::catch_unwind::h52728a6ebc96df5e
                               at src\libstd/panic.rs:394
  26:           0x75946c - std::rt::lang_start_internal::ha1701ac7d300255b
                               at src\libstd/rt.rs:51
  27:           0x446d48 - main
  28:           0x4013c7 - _tmainCRTStartup
  29:           0x4014fb - mainCRTStartup
  30:     0x7fffbec47bd4 - _report_error
  31:     0x7fffbf3ece51 - _report_error
error: process didn't exit successfully: `target\release\examples\widgets.exe` (exit code: 101)

```

</p>
</details>

Edit: I just realised this bug is only present in alpha4. Should bugs in alpha4 already be reported or is this still too much of a work in progress?

**Comment by FloVanGH** [comment]
Thank you for the report. That will be fixed.

**Comment by FloVanGH** [comment]
fixed

**Comment by arctic-alpaca** [comment]
This does fix the panic but the one off to the right behaviour remains.
I created a PR here #345 to fix this. I'm not sure if this has any consequences for other parts but in my quick experiments with the widget example it worked as intended.
