### ISSUE TITLE
Changing a PasswordBox's text field fails to update the password, causing a crash

### ISSUE THREAD

**Issue by Autofire** [redox-os/orbtk#412]
**Describe the bug**
Modifying the text field of a PasswordBox does not properly update the text with in the widget. The asterisks do not go away, and if the new length is shorter than the old length, attempting to edit the password will cause the application to crash.

**To Reproduce**
1. Clone `https://github.com/Autofire/OrbTk-PasswordBox-Bug.git`
2. Run the project.
3. Type something in the password field.
4. Click clear button.
5. Type something else in the password field.
6. Observe crash.

**Expected behavior**
On step four, the contents of the password box should reset.

**Screenshots**
![crash](https://user-images.githubusercontent.com/7464159/101223654-59a9b380-3641-11eb-9409-221bd76969f4.gif)

**Other notes**
At one point, I think I ran into similar behavior with TextBox as well, but it seems so gone away. If I can figure how to reproduce this with a TextBox, all make a new bug report or update this one.

It's possible I'm doing this in the wrong way, and I know my sample project is probably more convoluted than it needs to be. However, this does mirror my project which I encountered this bug in. I would appreciate a workaround, but I can use a TextBox for the time being.

**Condensed trace**
```
    Finished release [optimized] target(s) in 0.26s
     Running `target\release\password-bug.exe`
thread 'main' panicked at 'insertion index (is 5) should be <= len (is 0)', library\alloc\src\vec.rs:1018:13
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src\panicking.rs:85
   2: alloc::vec::{{impl}}::insert::assert_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\alloc\src\vec.rs:1018
   3: orbtk_utils::string16::String16::insert_str
   4: dces::component::string_component_store::StringComponentStore::register
   5: <orbtk_widgets::behaviors::text_behavior::TextBehaviorState as orbtk_api::widget_base::state::State>::messages
   6: ZN220_$LT$orbtk_api..systems..message_system..MessageSystem$u20$as$u20$dces..system..System$LT$orbtk_tree..Tree$C$dces..component..string_component_store..StringComponentStore$C$or
btk_render..platform..RenderContext2D$GT$$GT$16run_with_context17h9e69149a9
   7: dces::world::World<E,C,Ctx>::run_with_context
   8: orbtk_shell::platform::Shell<A>::run
   9: orbtk_api::application::Application::run
  10: orbtk_api::event::event_adapter::EventAdapter::push_event_direct
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\release\password-bug.exe` (exit code: 101)
```

**Full trace**
```
    Finished release [optimized] target(s) in 0.26s
     Running `target\release\password-bug.exe`
thread 'main' panicked at 'insertion index (is 5) should be <= len (is 0)', library\alloc\src\vec.rs:1018:13
stack backtrace:
   0:     0x7ff6081c2bd9 - std::backtrace_rs::backtrace::dbghelp::trace
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
   1:     0x7ff6081c2bd9 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff6081c2bd9 - std::sys_common::backtrace::_print_fmt
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace.rs:79
   3:     0x7ff6081c2bd9 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace.rs:58
   4:     0x7ff6081d731b - core::fmt::write
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src\fmt\mod.rs:1080
   5:     0x7ff6081c01c8 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\io\mod.rs:1516
   6:     0x7ff6081c56a4 - std::sys_common::backtrace::_print
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace.rs:61
   7:     0x7ff6081c56a4 - std::sys_common::backtrace::print
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace.rs:48
   8:     0x7ff6081c56a4 - std::panicking::default_hook::{{closure}}
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:208
   9:     0x7ff6081c5288 - std::panicking::default_hook
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:227
  10:     0x7ff6081c5f5f - std::panicking::rust_panic_with_hook
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:577
  11:     0x7ff6081c5ac5 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:484
  12:     0x7ff6081c34bf - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace.rs:153
  13:     0x7ff6081c5a79 - std::panicking::begin_panic_handler
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:483
  14:     0x7ff6081d5ae0 - core::panicking::panic_fmt
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src\panicking.rs:85
  15:     0x7ff6081d087b - alloc::vec::{{impl}}::insert::assert_failed
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\alloc\src\vec.rs:1018
  16:     0x7ff6081a0cdc - orbtk_utils::string16::String16::insert_str::h77718a5be60ea8a0
  17:     0x7ff6080b915d - dces::component::string_component_store::StringComponentStore::register::hf63e99bf02314d05
  18:     0x7ff6080bbd63 - <orbtk_widgets::behaviors::text_behavior::TextBehaviorState as orbtk_api::widget_base::state::State>::messages::hba1231794f664c0c
  19:     0x7ff6081122fb - ZN220_$LT$orbtk_api..systems..message_system..MessageSystem$u20$as$u20$dces..system..System$LT$orbtk_tree..Tree$C$dces..component..string_component_store..Stri
ngComponentStore$C$orbtk_render..platform..RenderContext2D$GT$$GT$16run_with_context17h9e69149a9
  20:     0x7ff6080ff5fa - dces::world::World<E,C,Ctx>::run_with_context::hae8ab9d06dcdcba3
  21:     0x7ff6080fdf30 - orbtk_shell::platform::Shell<A>::run::hbd1e3d30ec9e8b4f
  22:     0x7ff6080e9b5f - orbtk_api::application::Application::run::h98f07ea79aa4e39a
  23:     0x7ff60802e58e - orbtk_api::event::event_adapter::EventAdapter::push_event_direct::h8331db525637550e
  24:     0x7ff608040b06 - std::sys_common::backtrace::__rust_begin_short_backtrace::h585b406dbd4f4902
  25:     0x7ff60803bb7c - std::rt::lang_start::{{closure}}::hf890a0f1457cc2a2
  26:     0x7ff6081c6163 - core::ops::function::impls::{{impl}}::call_once
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\core\src\ops\function.rs:280
  27:     0x7ff6081c6163 - std::panicking::try::do_call
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:381
  28:     0x7ff6081c6163 - std::panicking::try
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:345
  29:     0x7ff6081c6163 - std::panic::catch_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panic.rs:382
  30:     0x7ff6081c6163 - std::rt::lang_start_internal
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\rt.rs:51
  31:     0x7ff60802e5c7 - main
  32:     0x7ff6082b8624 - invoke_main
                               at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  33:     0x7ff6082b8624 - __scrt_common_main_seh
                               at d:\agent\_work\63\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  34:     0x7ffb0bc27c24 - BaseThreadInitThunk
  35:     0x7ffb0cc8d4d1 - RtlUserThreadStart
error: process didn't exit successfully: `target\release\password-bug.exe` (exit code: 101)
```

**Comment by kivimango** [comment]
Thanks for reporting, i will look into it.The PasswordBox and the TextBox shares the same TextBehavior.
