### ISSUE TITLE
Update failed because input buffer is too small

### ISSUE THREAD

**Issue by hanckmann** [redox-os/orbtk#96]
I just did a clone of the repo and typed: cargo run --example widgets          

This was the result: Update failed because input buffer is too small. Required size for 956 x 1036 window (1x scale) is 3961664 bytes but the size of the input buffer has the size 1366560 bytes

This is the backtrace when run with `export RUST_BACKTRACE=1`:
```

λ ~/Projects/rust/orbtk/ develop cargo run --example widgets          
   Compiling autocfg v0.1.7
   Compiling libc v0.2.65
   Compiling semver-parser v0.7.0
   Compiling rand_core v0.4.2
   Compiling cfg-if v0.1.10
   Compiling byteorder v1.3.2
   Compiling lazy_static v1.4.0
   Compiling proc-macro2 v1.0.6
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.8
   Compiling proc-macro2 v0.4.30
   Compiling bitflags v1.2.1
   Compiling scopeguard v1.0.0
   Compiling unicode-xid v0.1.0
   Compiling siphasher v0.2.3
   Compiling crc32fast v1.2.0
   Compiling rayon-core v1.6.1
   Compiling syn v0.15.44
   Compiling adler32 v1.0.4
   Compiling unicode-xid v0.0.4
   Compiling quote v0.3.15
   Compiling arrayvec v0.4.12
   Compiling num-derive v0.2.5
   Compiling nodrop v0.1.14
   Compiling lzw v0.10.0
   Compiling maybe-uninit v2.0.0
   Compiling pkg-config v0.3.17
   Compiling either v1.5.3
   Compiling procedural-masquerade v0.1.6
   Compiling cc v1.0.47
   Compiling color_quant v1.0.1
   Compiling orbtk-utils v0.3.1-alpha2 (/home/patrick/Projects/rust/orbtk/crates/utils)
   Compiling scoped_threadpool v0.1.9
   Compiling matches v0.1.8
   Compiling arrayvec v0.5.1
   Compiling typed-arena v1.7.0
   Compiling sw-composite v0.7.2
   Compiling serde v1.0.103
   Compiling dces v0.2.0 (https://gitlab.redox-os.org/redox-os/dces-rust.git?branch=develop#fb2c2638)
   Compiling spin_sleep v0.3.7
   Compiling approx v0.1.1
   Compiling static_assertions v0.2.5
   Compiling semver v0.9.0
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling num-traits v0.2.10
   Compiling crossbeam-utils v0.7.0
   Compiling crossbeam-epoch v0.8.0
   Compiling num-integer v0.1.41
   Compiling rand_pcg v0.1.2
   Compiling rand_chacha v0.1.1
   Compiling rand v0.6.5
   Compiling num-rational v0.2.2
   Compiling num-iter v0.1.39
   Compiling phf_shared v0.7.24
   Compiling inflate v0.4.5
   Compiling synom v0.11.3
   Compiling gif v0.10.3
   Compiling x11-dl v2.18.4
   Compiling orbtk-tree v0.3.1-alpha2 (/home/patrick/Projects/rust/orbtk/crates/tree)
   Compiling rustc_version v0.2.3
   Compiling rand_hc v0.1.0
   Compiling rand_isaac v0.1.1
   Compiling rand_xorshift v0.1.1
   Compiling phf v0.7.24
   Compiling syn v0.11.11
   Compiling minifb v0.13.0
   Compiling memoffset v0.5.3
   Compiling cast v0.2.3
   Compiling vek v0.9.11
   Compiling quote v1.0.2
   Compiling deflate v0.7.20
   Compiling stb_truetype v0.3.1
   Compiling base64 v0.10.1
   Compiling rand_os v0.1.3
   Compiling num_cpus v1.11.1
   Compiling time v0.1.42
   Compiling dirs-sys v0.3.4
   Compiling quote v0.6.13
   Compiling png v0.15.1
   Compiling crossbeam-queue v0.2.0
   Compiling euclid v0.20.4
   Compiling ordered-float v1.0.2
   Compiling approx v0.3.2
   Compiling num-traits v0.1.43
   Compiling dirs v2.0.2
   Compiling cssparser v0.17.0
   Compiling rusttype v0.8.2
   Compiling lyon_geom v0.14.1
   Compiling phf_generator v0.7.24
   Compiling raqote v0.7.6
   Compiling phf_codegen v0.7.24
   Compiling crossbeam-deque v0.7.2
   Compiling euc v0.4.2
   Compiling rayon v1.2.1
   Compiling jpeg-decoder v0.1.16
   Compiling tiff v0.3.1
   Compiling image v0.22.3
   Compiling cssparser-macros v0.3.6
   Compiling serde_derive v1.0.103
   Compiling derive_more v0.99.2
   Compiling orbtk-proc-macros v0.3.1-alpha2 (/home/patrick/Projects/rust/orbtk/crates/proc-macros)
   Compiling orbtk-render v0.3.1-alpha2 (/home/patrick/Projects/rust/orbtk/crates/render)
   Compiling orbtk-shell v0.3.1-alpha2 (/home/patrick/Projects/rust/orbtk/crates/shell)
   Compiling orbtk-css-engine v0.3.1-alpha2 (/home/patrick/Projects/rust/orbtk/crates/css-engine)
   Compiling orbtk-theme v0.3.1-alpha2 (/home/patrick/Projects/rust/orbtk/crates/theme)
   Compiling ron v0.5.1
   Compiling orbtk-api v0.3.1-alpha2 (/home/patrick/Projects/rust/orbtk/crates/api)
   Compiling orbtk-widgets v0.3.1-alpha2 (/home/patrick/Projects/rust/orbtk/crates/widgets)
   Compiling orbtk v0.3.1-alpha1 (/home/patrick/Projects/rust/orbtk)
    Finished dev [optimized + debuginfo] target(s) in 4m 13s
     Running `target/debug/examples/widgets`
UnexpectedToken(Number { has_sign: false, value: 16.0, int_value: None })
Error occured in `border-radius: 16.0;`
UnexpectedToken(Number { has_sign: false, value: 16.0, int_value: None })
Error occured in `border-radius: 16.0;`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UpdateFailed("Update failed because input buffer is too small. Required size for 956 x 1036 window (1x scale) is 3961664 bytes but the size of the input buffer has the size 1366560 bytes")', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1030
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  12: rust_begin_unwind
             at src/libstd/panicking.rs:307
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::unwrap
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libcore/result.rs:933
  16: orbtk_shell::platform::WindowShell<A>::flip
             at ./crates/shell/src/minifb/mod.rs:274
  17: orbtk_shell::platform::ShellRunner<A>::run
             at ./crates/shell/src/minifb/mod.rs:331
  18: orbtk_api::application::Application::run
             at crates/api/src/application/mod.rs:234
  19: widgets::main
             at examples/widgets.rs:411
  20: std::rt::lang_start::{{closure}}
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  21: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:49
  22: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  23: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  24: std::panicking::try
             at src/libstd/panicking.rs:271
  25: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  26: std::rt::lang_start_internal
             at src/libstd/rt.rs:48
  27: std::rt::lang_start
             at /rustc/4560ea788cb760f0a34127156c78e2552949f734/src/libstd/rt.rs:64
  28: __libc_start_main
  29: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```
I am a rust beginner, so I am not sure how to resolve this or what more info you need. Please let me know and I will provide it!

**Comment by FloVanGH** [comment]
@hanckmann welcome and thank your for the report. Which operating system / desktop envioment do you use.

**Comment by hanckmann** [comment]
Yes, I should have provided that to begin with.
I am on ArchLinux
```
λ ~/ uname -a
Linux copernicus 5.3.13-arch1-1 #1 SMP PREEMPT Sun, 24 Nov 2019 10:15:50 +0000 x86_64 GNU/Linux
```
I run Xfce4 with i3 as wm on Xorg with Intel:

- xf86-video-intel 1:2.99.917+897+g0867eea6-
- extra/xorg-server 1.20.6-1
- xfce4 4.14.0-1
- i3-wm 4.17.1-1

**Comment by FloVanGH** [comment]
@hanckmann could you do me a favor and could you check if you have the same issue with the noise example of https://github.com/emoon/rust_minifb. Does it happen after start or after resize the window?

**Comment by hanckmann** [comment]
Hi,
1) I just tested the rust-minifb noise example, and that runs without issues.
2) Good catch with the question on "after start or after resize"!
So, I use i3-wm as a window manager. It is a tiling window manager and resizes the window when created (I am not too much into those details though).
I forced i3-wm to open the window as floating window, and than the window is created. After this, I can change the size and make it full screen (by disabling the floating property of the window). The application runs without an issue.
However, when **starting** as a tiling window (not floating), the window crashes with the error as described before.

For now I can live with that and will try to use orbtk as GUI environment.

I would be happy to help finding the exact issue. Just let me know how!

**Comment by hanckmann** [comment]
Aah, and just for your info. The rust-minifb noise example runs smoothly also when started as tiling window.

**Comment by FloVanGH** [comment]
@hanckmann thank you. The issue should be fixed now it was related to minifb https://github.com/emoon/rust_minifb/issues/105.

**Comment by hanckmann** [comment]
Thanks it works now indeed.
